/**
 * Preview token — HMAC-SHA256 signed URL token for GET /preview/:id
 *
 * Format: `${projectId}:${expMs}:${hmacHex}` where hmacHex is
 * HMAC-SHA256(`${projectId}:${expMs}`, secret). Generated by the
 * video-v4-orchestrator edge (same algorithm, Web Crypto) and verified here.
 * R5 follow-up: preview is never public — expired/invalid tokens are rejected.
 */
import { createHmac, timingSafeEqual } from "node:crypto";

function hmac(projectId, exp, secret) {
  return createHmac("sha256", secret).update(`${projectId}:${exp}`).digest("hex");
}

export function createPreviewToken(projectId, secret, { ttlMs = 24 * 3600 * 1000, now = Date.now() } = {}) {
  const exp = now + ttlMs;
  return `${projectId}:${exp}:${hmac(projectId, exp, secret)}`;
}

export function verifyPreviewToken(token, projectId, secret, now = Date.now()) {
  if (typeof token !== "string") return false;
  const parts = token.split(":");
  if (parts.length !== 3) return false;
  const [pid, expRaw, sig] = parts;
  if (pid !== projectId) return false;
  const exp = Number(expRaw);
  if (!Number.isFinite(exp) || exp <= now) return false;
  const expected = hmac(pid, exp, secret);
  if (sig.length !== expected.length) return false;
  try {
    return timingSafeEqual(Buffer.from(sig), Buffer.from(expected));
  } catch {
    return false;
  }
}
